version: '3.8'
services:
  server:
    build: ./server
    container_name: web-server
    environment:
      PORT: "8080"
    restart: always
    ports:
      - "8080:8080"
    networks:
      - net
  client:
    depends_on:
      - server
    build: ./client
    container_name: web-client
    environment:
      NUM: "1"
      COUNT: "1"
    restart: always
    networks:
      - net
networks:
  net:
    driver: bridge
